#ifndef _SOUND_H
#define _SOUND_H


void sound_load(void);
void sound_destroy(void);
void play_demosound(void);
void play_mcskid(INT32 x, INT32 y);
void play_spring(INT32 x, INT32 y);
void play_mcwall(INT32 x, INT32 y);
void play_mcfall(INT32 x, INT32 y);
void play_mcdrain(void);
void play_blub(INT32 x, INT32 y);
void play_door(void);
void play_switch(void);
void play_bonus(INT32 x, INT32 y);
void play_warp(void);
void play_wheel(INT32 x, INT32 y);
void play_appel(INT32 x, INT32 y);
void play_mcdood(INT32 x, INT32 y);
void play_mcfart(INT32 x, INT32 y);
void play_shoot(INT32 x, INT32 y);
void play_rumble(void);
void stop_rumble(void);
void rumblesoundsofter();
void rumblesoundharder();
void rumblevolume(INT32 volume);
void play_waterval(void);
void stop_waterval(void);
void prox_waterval_volume(INT32 lvolume, INT32 rvolume);
void real_waterval_volume(void);
void play_mcloop(UINT16 sapflg, INT32 x, INT32 y);
void play_mcloop1(INT32 x, INT32 y);
void play_mcloop2(INT32 x, INT32 y);
void play_sapstap1(INT32 x, INT32 y);
void play_sapstap2(INT32 x, INT32 y);
void play_helmlp1(INT32 x, INT32 y);
void play_helmlp2(INT32 x, INT32 y);
void play_houtpunt(INT32 x, INT32 y);
void play_ball(INT32 x, INT32 y);
void play_segmshot(INT32 x, INT32 y);
void play_segmexpl(INT32 x, INT32 y);
void play_segmhit(INT32 x, INT32 y);
void play_tanden(INT32 x, INT32 y);
void stop_cammove(void);
void play_cammove(void);
void play_camstart(void);
void play_camstop(void);
void play_tandenm(INT32 x, INT32 y);
void play_graspod(INT32 x, INT32 y);
void play_heks(INT32 x, INT32 y);
void play_madeit(void);
void play_bat(void);
void prox_bat_volume(INT32 lvolume, INT32 rvolume);
void real_bat_volume(void);
void play_vogel(void);
void prox_vogel_volume(INT32 lvolume, INT32 rvolume);
void real_vogel_volume(void);
void play_vuur(void);
void prox_vuur_volume(INT32 lvolume, INT32 rvolume);
void real_vuur_volume(void);
void play_drilboor(void);
void prox_drilboor_volume(INT32 lvolume, INT32 rvolume);
void real_drilboor_volume(void);
void play_loopband(void);
void prox_loopband_volume(INT32 lvolume, INT32 rvolume);
void real_loopband_volume(void);
void play_bee(void);
void prox_bee_volume(INT32 lvolume, INT32 rvolume);
void real_bee_volume(void);
void play_bee2(void);
void prox_bee2_volume(INT32 lvolume, INT32 rvolume);
void real_bee2_volume(void);
void play_vlamwerp(void);
void prox_vlamwerp_volume(INT32 lvolume, INT32 rvolume);
void real_vlamwerp_volume(void);
void play_ventltor(void);
void prox_ventltor_volume(INT32 lvolume, INT32 rvolume);
void real_ventltor_volume(void);
void play_ptoei(INT32 x, INT32 y);
void play_bigexp(INT32 x, INT32 y);
void play_restart(void);
void set_backpak_volume(INT32 volume);
void play_backpak(void);
void play_smexp(INT32 x, INT32 y);
void play_schuif(void);
void play_cannon(INT32 x, INT32 y);
void play_gewicht(INT32 x, INT32 y);
void play_stroom(void);
void prox_stroom_volume(INT32 lvolume, INT32 rvolume);
void real_stroom_volume(void);
void play_chemo(void);
void prox_chemo_volume(INT32 lvolume, INT32 rvolume);
void real_chemo_volume(void);
void play_tik(void);
void play_tak(void);
void play_raket(INT32 x, INT32 y);
void play_chemo2(void);
void play_helmdood(INT32 x, INT32 y);
void play_ketting(INT32 x, INT32 y);
void chemo2volume(INT32 volume);
void play_dimndsht(INT32 x, INT32 y);
void play_glasblok(INT32 x, INT32 y);
void play_hyprlift(INT32 x, INT32 y);
void play_lightwav(INT32 x, INT32 y);
void play_morphsht(INT32 x, INT32 y);
void play_mushup(INT32 x, INT32 y);
void play_mushdwn(INT32 x, INT32 y);
void play_plntlft(INT32 x, INT32 y);
void play_pltfdwn(INT32 x, INT32 y);
void play_pltfup(INT32 x, INT32 y);
void play_qbert1(INT32 x, INT32 y);
void play_qbert2(INT32 x, INT32 y);
void play_roltnlp(void);
void play_slowlift(void);
void play_tangjmp(INT32 x, INT32 y);
void play_tangclos(INT32 x, INT32 y);
void play_woeiwoei(void);
void play_heatsnkr(void);
void play_slowlift(void);
void prox_slowlift_volume(INT32 lvolume, INT32 rvolume);
void real_slowlift_volume(void);
void play_woeiwoei(void);
void woeiwoeivolume(INT32 volume);
void play_roltnlp(void);
void prox_roltnlp_volume(INT32 lvolume, INT32 rvolume);
void real_roltnlp_volume(void);
void play_heatsnkr(void);
void prox_heatsnkr_volume(INT32 lvolume, INT32 rvolume);
void real_heatsnkr_volume(void);



#endif

